import React, { useEffect, useState } from 'react'
import { dummyPublishedImages } from '../assets/assets';
import Loading from './Loading';

const Community = () => {
    const [images, setImages] = useState([]);
    const [loading, setLoading] = useState(true); 

    const fetchImages = async () => {
        // Simulate a slight delay for better UX
        setTimeout(() => {
            setImages(dummyPublishedImages);
            setLoading(false);
        }, 1500);
    }

    useEffect(() => {
        fetchImages();
    }, [])

    if (loading) return <Loading />

    return (
        <div className='flex-1 h-screen overflow-y-auto bg-white dark:bg-transparent custom-scrollbar'>
            <div className='p-8 pt-16 xl:px-20 2xl:px-32 w-full mx-auto'>
                
                {/* Header Section */}
                <div className='mb-12'>
                    <h1 className='text-4xl md:text-5xl font-black tracking-tighter text-gray-900 dark:text-white'>
                        Community <span className='text-purple-500'>Gallery</span>
                    </h1>
                    <p className='mt-3 text-gray-500 dark:text-[#666] font-medium max-w-lg'>
                        Explore the most creative images generated by our community using Gemini AI.
                    </p>
                </div>

                {images.length > 0 ? (
                    /* 3. The Pro Grid Layout */
                    <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4 gap-6'>
                        {images.map((image, index) => (
                            <div 
                                key={index} 
                                className='group relative aspect-square overflow-hidden rounded-3xl bg-gray-100 dark:bg-[#1A1A1A] border border-gray-200 dark:border-white/10 shadow-sm transition-all duration-500 hover:shadow-2xl hover:shadow-purple-500/20'
                            >
                                {/* Image */}
                                <img 
                                    src={image.imageUrl} 
                                    alt={`Community Gen ${index}`} 
                                    className='w-full h-full object-cover transition-transform duration-700 group-hover:scale-110'
                                />

                                {/* Hover Overlay - Pro UX */}
                                <div className='absolute inset-0 bg-gradient-to-t from-black/80 via-black/20 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex flex-col justify-end p-6'>
                                    <div className='flex items-center justify-between'>
                                        <button className='bg-white/10 backdrop-blur-md text-white text-[10px] font-bold uppercase tracking-widest px-4 py-2 rounded-full border border-white/20 hover:bg-white hover:text-black transition-all'>
                                            View Prompt
                                        </button>
                                        <div className='w-8 h-8 rounded-full bg-purple-500 flex items-center justify-center text-white text-xs shadow-lg'>
                                            ✨
                                        </div>
                                        <p>creaed by : {image.userName}</p>
                                    </div>
                                </div>
                            </div>
                        ))}
                    </div>
                ) : (
                    /* Empty State */
                    <div className='flex flex-col items-center justify-center h-[50vh] text-center'>
                        <div className='w-20 h-20 bg-gray-100 dark:bg-white/5 rounded-full flex items-center justify-center mb-4'>
                            <span className='text-4xl'>🖼️</span>
                        </div>
                        <h3 className='text-xl font-bold text-gray-800 dark:text-white'>No images yet</h3>
                        <p className='text-gray-500 mt-2'>Be the first to publish an AI masterpiece!</p>
                    </div>
                )}
            </div>
        </div>
    )
}

export default Community;